provider:
  name: faas
  gateway: https://md-gw.team-serverless.xyz

functions:
  system-github-event:
    lang: go
<<<<<<< HEAD
    handler: ./github-push
    image: martindekov/github-push:0.6.0
=======
    handler: ./github-event
    image: functions/github-event:0.6.0
>>>>>>> 1821c7995ba1c5a82e492a40d9886a56f4a1dcca
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
    environment:
      validate_hmac: true
      write_debug: true
      read_debug: true
    environment_file:
      - github.yml
      - gateway_config.yml
    secrets:
      - github-webhook-secret
      - payload-secret

<<<<<<< HEAD
  system-github-event:
=======
  github-push:
>>>>>>> 1821c7995ba1c5a82e492a40d9886a56f4a1dcca
    lang: go
    handler: ./github-push
    image: functions/github-push:0.6.1
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
    environment:
      validate_hmac: true
<<<<<<< HEAD
=======
      read_timeout: 10s
      write_timeout: 10s
>>>>>>> 1821c7995ba1c5a82e492a40d9886a56f4a1dcca
      write_debug: true
      read_debug: true
      validate_customers: true
    environment_file:
      - gateway_config.yml
      - github.yml
    secrets:
      - github-webhook-secret
      - payload-secret


  git-tar:
    lang: dockerfile
    handler: ./git-tar
    image: functions/of-git-tar:0.8.3
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
    environment:
      read_timeout: 15m
      write_timeout: 15m
      write_debug: true
      read_debug: true
    environment_file:
      - gateway_config.yml
      - github.yml
    secrets:
      - github-webhook-secret
      - payload-secret
      - private-key

  buildshiprun:
    lang: go
    handler: ./buildshiprun
<<<<<<< Updated upstream
<<<<<<< HEAD
    image: martindekov/of-buildshiprun:0.7.0
=======
    image: functions/of-buildshiprun:0.8.2
>>>>>>> 1821c7995ba1c5a82e492a40d9886a56f4a1dcca
=======
    image: functions/of-buildshiprun:0.7.0
>>>>>>> Stashed changes
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
    environment:
      read_timeout: 5m
      write_timeout: 5m
      write_debug: true
      read_debug: true
    environment_file:
      - buildshiprun_limits.yml
      - gateway_config.yml
      - github.yml
    secrets:
      - basic-auth-user
      - basic-auth-password
      - payload-secret
      - swarm-pull-secret

  garbage-collect:
    lang: go
    handler: ./garbage-collect
<<<<<<< HEAD
    image: martindekov/garbage-collect:0.4.0
=======
    image: functions/garbage-collect:0.4.1
>>>>>>> 1821c7995ba1c5a82e492a40d9886a56f4a1dcca
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
    environment:
      write_debug: true
      read_debug: true
      read_timeout: 30s
      write_timeout: 30s
    environment_file:
      - gateway_config.yml
    secrets:
      - basic-auth-user
      - basic-auth-password
      - payload-secret

  github-status:
    lang: go
    handler: ./github-status
    image: functions/github-status:0.2.2
    labels:
      role: openfaas-system
    environment:
      write_debug: true
      read_debug: true
      combine_output: false
      validate_hmac: true
      debug_token: true
    environment_file:
      - gateway_config.yml
      - github.yml
    secrets:
      - private-key
      - payload-secret

  import-secrets:
    lang: go
    handler: ./import-secrets
<<<<<<< HEAD
    image: martindekov/import-secrets:0.3.0
=======
    image: functions/import-secrets:0.3.1
>>>>>>> 1821c7995ba1c5a82e492a40d9886a56f4a1dcca
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
    openfaas-cloud: "1"
    environment:
      write_debug: true
      read_debug: true
      validate_hmac: true
      combined_output: false
    environment_file:
      - github.yml
    secrets:
      - payload-secret

  pipeline-log:
    lang: go
    handler: ./pipeline-log
    image: functions/pipeline-log:0.3.2
    labels:
      role: openfaas-system
    environment:
      write_debug: true
      read_debug: true
      combine_output: false
    environment_file:
      - gateway_config.yml
    secrets:
      - s3-access-key
      - s3-secret-key
      - payload-secret

  list-functions:
    lang: go
    handler: ./list-functions
<<<<<<< HEAD
    image: martindekov/list-functions:0.4.4
=======
    image: functions/list-functions:0.4.6
>>>>>>> 1821c7995ba1c5a82e492a40d9886a56f4a1dcca
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
    environment:
      write_debug: true
      read_debug: true
    environment_file:
      - gateway_config.yml
    secrets:
      - basic-auth-user
      - basic-auth-password

  audit-event:
    lang: go
    handler: ./audit-event
    image: martindekov/audit-event:0.1.1
    labels:
      openfaas-cloud: "1"
    environment_file:
      - slack.yml

  echo:
    skip_build: true
    image: functions/alpine:latest
    fprocess: cat
    environment:
      write_debug: true
      read_debug: true

  system-metrics:
    lang: go
    handler: ./system-metrics
    image: functions/system-metrics:0.1.0
    environment_file:
      - gateway_config.yml
    environment:
      content_type: "application/json"

