provider:
  name: faas
  gateway: http://md-gw.team-serverless.xyz

functions:
  github-push:
    lang: go
    handler: ./github-push
    image: martindekov/github-push:0.6.0
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
    environment:
      validate_hmac: true
      read_timeout: 10s
      write_timeout: 10s
      write_debug: true
      read_debug: true
      validate_customers: true
    environment_file:
      - gateway_config.yml
      - github.yml
    secrets:
      - github-webhook-secret
      - payload-secret

  github-event:
    lang: go
    handler: ./github-event
    image: martindekov/github-event:0.5.0
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
    environment:
      write_debug: true
      read_debug: true
    environment_file:
      - github.yml
      - gateway_config.yml
    secrets:
      - github-webhook-secret
      - payload-secret

  git-tar:
    lang: dockerfile
    handler: ./git-tar
<<<<<<< 346af346d2df74dab8bac3e25912696a9010bb9f
    image: functions/of-git-tar:0.8.2
=======
    image: martindekov/of-git-tar:0.8.0
>>>>>>> Add my own config
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
    environment:
      read_timeout: 15m
      write_timeout: 15m
      write_debug: true
      read_debug: true
    environment_file:
      - gateway_config.yml
      - github.yml
    secrets:
      - github-webhook-secret
      - payload-secret
      - private-key

  buildshiprun:
    lang: go
    handler: ./buildshiprun
    image: martindekov/of-buildshiprun:0.7.0
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
    environment:
      read_timeout: 5m
      write_timeout: 5m
      write_debug: true
      read_debug: true
    environment_file:
      - buildshiprun_limits_swarm.yml
      - gateway_config.yml
      - github.yml
    secrets:
      - basic-auth-user
      - basic-auth-password
      - payload-secret
      - swarm-pull-secret

  garbage-collect:
    lang: go
    handler: ./garbage-collect
    image: martindekov/garbage-collect:0.4.0
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
    environment:
      write_debug: true
      read_debug: true
      read_timeout: 30s
      write_timeout: 30s
    environment_file:
      - gateway_config.yml
    secrets:
      - basic-auth-user
      - basic-auth-password
      - payload-secret

  github-status:
    lang: go
    handler: ./github-status
<<<<<<< 346af346d2df74dab8bac3e25912696a9010bb9f
    image: functions/github-status:0.2.1
    labels:
      role: openfaas-system
=======
    image: martindekov/github-status:0.2.0
>>>>>>> Add my own config
    environment:
      write_debug: true
      read_debug: true
      combine_output: false
      validate_hmac: true
      debug_token: true
    environment_file:
      - gateway_config.yml
      - github.yml
    secrets:
      - private-key
      - payload-secret

  import-secrets:
    lang: go
    handler: ./import-secrets
    image: martindekov/import-secrets:0.3.0
    labels:
<<<<<<< 346af346d2df74dab8bac3e25912696a9010bb9f
      openfaas-cloud: "1"
      role: openfaas-system
=======
    openfaas-cloud: "1"
>>>>>>> Add my own config
    environment:
      write_debug: true
      read_debug: true
      validate_hmac: true
      combined_output: false
    environment_file:
      - github.yml
    secrets:
      - payload-secret

  pipeline-log:
    lang: go
    handler: ./pipeline-log
<<<<<<< 346af346d2df74dab8bac3e25912696a9010bb9f
    image: functions/pipeline-log:0.3.1
    labels:
      role: openfaas-system
=======
    image: martindekov/pipeline-log:0.3.1
>>>>>>> Add my own config
    environment:
      write_debug: true
      read_debug: true
      combine_output: false
    environment_file:
      - gateway_config.yml
    secrets:
      - s3-access-key
      - s3-secret-key
      - payload-secret

  list-functions:
    lang: go
    handler: ./list-functions
    image: martindekov/list-functions:0.4.4
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
    environment:
      write_debug: true
      read_debug: true
    environment_file:
      - gateway_config.yml
    secrets:
      - basic-auth-user
      - basic-auth-password

  audit-event:
    lang: go
    handler: ./audit-event
    image: martindekov/audit-event:0.1.1
    labels:
      openfaas-cloud: "1"
    environment_file:
      - slack.yml

  echo:
    skip_build: true
    image: functions/alpine:latest
    fprocess: cat
    environment:
      write_debug: true
      read_debug: true

